### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by mtllr** [b3j0f/aop#1]
Hi B3j0f,

I am a python 2.7 user and upon executing `from b3j0f.aop import weave` I get `ImportError: No module named builtins`

I suspect the problem is a python 2 to 3 compatibility issue and you might want to patch this in 
joinpoint.py, line 44:

``` python
try:
    import builtins
except ImportError:
    import future_builtins as builtins
```

or scrapping the line 44 and replacing under import six line 52 with

``` python
if PY2:
    import future_builtins as builtins
else:  #PY3
    import builtins
```

Tested with your documented example min/max and worked for me. ;-)
Martin

**Comment by b3j0f** [comment]
Ok, thank you very much Martin !

It is fixed :)
