### ISSUE TITLE
Example for regex targets

### ISSUE THREAD

**Issue by jfloff** [b3j0f/aop#2]
Hello,

First of all great effort in standardizing python's AOP function, and great state-of-the-art roundup. 

I have a question, I want to make a pointcut target based on a regex pattern, something like this:

``` python
weave(target="min*", advices=double_advice)
```

Could you provide an example of how to do this with your package? 

Thanks,

**Comment by b3j0f** [comment]
Hello,
thank you for your good remark !

In this library, pointcut is for method names.

I added an example on the [README](https://github.com/b3j0f/aop/blob/master/README.rst#how-to-change-behaviour-of-class-methods-with-a-pointcut-)

**Comment by jfloff** [comment]
Are regex pointcut interceptions exclusive for class methods?

**Comment by b3j0f** [comment]
I didn't know it might be possible in AOP to use regex pointcuts for something else than methods (not only class methods).

I have a solution for you...

If I right understood your question, you want to apply the interception on all functions with a name starting by "min"
Therefore, you have to create your class with global functions, like that :

`tmp = type('tmp', (object), globals())`
`weave(tmp, pointcuts='min.*', advices=double_advice)`

It might work...
